# Generated by Django 5.1.2 on 2024-10-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamfake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
    ]
