# Generated by Django 5.1.2 on 2024-10-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamfake', '0003_aluno_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nota1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nota2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nota3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
