# Generated by Django 5.1.2 on 2024-10-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamfake', '0006_alter_aluno_nota1_alter_aluno_nota2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('duracao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
            ],
        ),
    ]
